### ISSUE TITLE
AVQA dimensional error

### ISSUE THREAD

**Issue by liey1** [GenjiB/LAVISH#12]
i have same error：
Traceback (most recent call last):
  File "/LAVISH-main/AVQA/net_grd_avst/net_avst.py", line 318, in forward
    audio = repeat(audio, 'b t len dim -> b t c len dim', c=3)
  File "/root/anaconda3/lib/python3.9/site-packages/einops/einops.py", line 533, in repeat
    return reduce(tensor, pattern, reduction='repeat', **axes_lengths)
  File "/root/anaconda3/lib/python3.9/site-packages/einops/einops.py", line 420, in reduce
    raise EinopsError(message + '\n {}'.format(e))
einops.EinopsError:  Error while processing repeat-reduction pattern "b t len dim -> b t c len dim".
 Input tensor shape: torch.Size([32, 10, 128]). Additional info: {'c': 3}.
 Expected 4 dimensions, got 3

this my command:

python net_grd_avst/main_avst.py --mode train --audio_dir=/AVQA/MUSIC_AVQA/MUSIC-AVQA-main/data/vggish/ --video_res14x14_dir=/AVQA/MUSIC_AVQA/MUSIC-AVQA-main/data/

plz help me

**Comment by GenjiB** [comment]
fixed thanks
