### ISSUE TITLE
avsbench shape not match

### ISSUE THREAD

**Issue by Everglow-ZJU** [GenjiB/LAVISH#13]
I try to run the code of Lavish on avs, but the following error occurs:

 
Traceback (most recent call last):
  File "/root/LAVISH/AVS/avs_scripts/avs_s4/train.py", line 247, in <module>
    output, visual_map_list, a_fea_list = model(imgs, audio_spec) # [bs*5, 1, 224, 224]
  File "/root/miniconda3/envs/LAVISH_AVS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/LAVISH_AVS/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/root/miniconda3/envs/LAVISH_AVS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/LAVISH/AVS/avs_scripts/avs_s4/model/PVT_AVSModel.py", line 492, in forward
    x = self.swin.norm(x)
  File "/root/miniconda3/envs/LAVISH_AVS/lib/python3.9/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/miniconda3/envs/LAVISH_AVS/lib/python3.9/site-packages/torch/nn/modules/normalization.py", line 169, in forward
    return F.layer_norm(
  File "/root/miniconda3/envs/LAVISH_AVS/lib/python3.9/site-packages/torch/nn/functional.py", line 2094, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps,
RuntimeError: Given normalized_shape=[1536], expected input with shape [*, 1536], but got input of size[20, 3, 192, 192]

**Comment by ShareWeb123** [comment]
I have encountered the same problem. May I ask if you have solved the problem?
